services:
  CaseAeC:
    image: caseaec:v1
    build:
      context: .
    container_name: CaseAeC
    restart: unless-stopped
    ports:
      - "3007:3007"
      - "8087:8087"
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Server=db-case;Database=CaseAeCDB;User Id=SA;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
    depends_on:
      - db-case
    networks:
      - CaseAeC-network

  db-case:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: CaseAeC-SQL
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - CaseAeC-network

  nginx:
    image: nginx:alpine
    container_name: CaseAeC-proxy
    restart: always
    ports:
      - "8088:80"
      - "2053:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - CaseAeC
    networks:
      - CaseAeC-network

networks:
  CaseAeC-network:

volumes:
  sql_data: